### ISSUE TITLE
Error on interstitial - Callback already registered

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#889]
When we were testing something else on Dev, we got an error and could only see the interstitial.

When checking the logs, we saw this error:

```
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: Traceback (most recent call last):
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: self._startRunCallbacks(fail)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: self._runCallbacks()
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: current.result = callback(current.result, *args, **kw)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: _inlineCallbacks(r, g, deferred)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: --- <exception caught here> ---
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: result = result.throwExceptionIntoGenerator(g)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: return g.throw(self.type, self.value, self.tb)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/leap.py", line 77, in setup
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: leap_session = yield create_leap_session(self._provider, user_auth.username, password, user_auth)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: result = result.throwExceptionIntoGenerator(g)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: return g.throw(self.type, self.value, self.tb)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/leap.py", line 41, in create_leap_session
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: leap_session = yield LeapSessionFactory(provider).create(username, password, auth)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: result = result.throwExceptionIntoGenerator(g)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: return g.throw(self.type, self.value, self.tb)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 40, in create
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: session = yield self._create_new_session(username, password, auth)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: result = g.send(result)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 63, in _create_new_session
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: leap_session = LeapSession(self._provider, auth, mail_store, soledad, keymanager, smtp_config)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 150, in __init__
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: register(events.KEYMANAGER_FINISHED_KEY_GENERATION, self._set_fresh_account, uid=self.account_email())
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/__init__.py", line 83, in register
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: return client.register(event, callback, uid, replace)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 524, in register
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: event, callback, uid=uid, replace=replace)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 435, in register
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: self, event, callback, uid=uid, replace=replace)
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 139, in register
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: raise CallbackAlreadyRegisteredError()
Dec 20 17:34:40 dev1 pixelated-user-agent[26390]: leap.common.events.errors.CallbackAlreadyRegisteredError:
```

This error happens because the [UA added a callback](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/config/sessions.py#L150) to mark that account as a fresh account if the account is a new one. But it [raise a exception](https://github.com/leapcode/leap_pycommon/blob/master/src/leap/common/events/client.py#L139) when a UUID associated with that callback is already registered. To do that we are using the email address as uuid. The class used to hold that callbacks is a singleton, so the instance persists until the application is restarted.

**Comment by tayanefernandes** [comment]
We found out that when some exception occurs during the services setup, the session is not being closed. We fixed that for the UploadKeyError, but the same can happen in other parts of the code.

**Comment by olabini** [comment]
I just created a PR #915 that moves the handling of exceptions further up to make sure that any kind of error during the login leads to the session being closed.

**Comment by olabini** [comment]
AFAICT this happened because a previous login generated an error which didn't clean up the registered event handler - and then the next time you logged in, it registered it again, causing the above exception. Since the code in #915/#920 has been merged, I think we can be reasonably certain that this problem won't happen again.

**Comment by olabini** [comment]
Actually, we can make this code slightly more robust - I'll submit a PR to do that instead.

**Comment by tuliocasagrande** [comment]
Hello @olabini, I tested #915/#920 locally (actually I should have done that before merging the PR, my bad) and we still have a problem when an exception is raised before returning the session, inside [create_leap_session](https://github.com/pixelated/pixelated-user-agent/blob/bcdfa584baa617025bf69acafe7e6576a8228912/service/pixelated/config/leap.py#L95).

I was considering to check for exceptions also inside `LeapSessionFactory.create`. For instance, if an error occurs inside [session.first_required_sync](https://github.com/pixelated/pixelated-user-agent/blob/bcdfa584baa617025bf69acafe7e6576a8228912/service/pixelated/config/sessions.py#L57), we have to close the session, but further up in the call stack we'll still have `leap_session = None`.

I think it's still important to ensure the session is closed, even with #936, because of `stop_background_jobs`, `soledad.close` and etc

Steps to test:

**Comment by tuliocasagrande** [comment]
I tested locally and it's working great.

Steps to reproduce my test:
- run locally against unstable
- ssh to unstable machine and kill soledad
- try to login via browser and check the logs. You'll get `Connection refused`.
- *previously at any subsequent logins, we were getting `CallbackAlreadyRegisteredError`*
- Restart soledad on unstable
- Login successful 🎉

**Comment by olabini** [comment]
Hey Tulio - your previous comment disappeared. Not sure why that happened - maybe Github swallowed it, or you removed it on purpose? Anyway, I'll look into it. I have a copy of the email with the text if you want the comment back.

**Comment by tuliocasagrande** [comment]
hello @olabini, thanks for noticing that. Actually I was writing and accidentally sent the comment incomplete.

I'll put here for reference:

> Hello @olabini, I tested #915/#920 locally (actually I should have done that before merging the PR, my bad) and we still have a problem when an exception is raised before returning the session, inside [create_leap_session](https://github.com/pixelated/pixelated-user-agent/blob/d9e9c8cd0c47ceb1883e7215dfcea055be391d96/service/pixelated/config/leap.py#L95).
> 
> I was considering to check for exceptions also inside [LeapSessionFactory.create](https://github.com/pixelated/pixelated-user-agent/blob/d9e9c8cd0c47ceb1883e7215dfcea055be391d96/service/pixelated/config/sessions.py#L49). For instance, if an error occurs inside session.first_required_sync, we have to close the session, but further up in the call stack we'll still have leap_session = None.
> 
> I think it's still important to ensure the session is closed, even with #936, because of stop_background_jobs, soledad.close and etc.
> 
> Steps to test:

What happened then is that I tested #936 and the `CallbackAlreadyRegisteredError` was gone!
It seems services such as `incoming_mail_fetcher` and `soledad` that are inside of `session.first_required_sync` can recover from an "incomplete login" and the only part that was missing is the one fixed on #936.

Because of this conclusion I removed my precocious/mistake comment. Sorry for the confusion.

**Comment by olabini** [comment]
Perfect, great! So there's nothing I need to look at here?

**Comment by tuliocasagrande** [comment]
@olabini Yeah! I think we can close this issue.

We are now closing the session when an error occurs, allowing the user to try again. Further steps will be to redirect the user back to the login page and show a proper error message #907.
